// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

type Message struct {
	ID   string
	Text string
}

type SentMessage struct {
	ID        string
	MessageID string
	Text      string
	Result    string
}
